[versions]
agp = "9.0.1"
activityKtx = "1.12.4"
webkit = "1.15.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
